version: '2'
  
volumes:
  osinstance4.cerberus.net:

networks:
  cerberusntw:

services:
  osinstance4.cerberus.net:
    extends:
      file: ../base/os-base.yaml
      service: os-base
    container_name: osinstance4.cerberus.net
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
    - ORDERER_HOST=osinstance4.cerberus.net
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../../../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../../../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance4.cerberus.net/msp/:/var/hyperledger/orderer/msp
    - ../../../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance4.cerberus.net/tls/:/var/hyperledger/orderer/tls
    - osinstance4.cerberus.net:/var/hyperledger/production/orderer
    depends_on:
    # add kafka instances
    networks:
    - cerberusntw
    ports:
    - 7450:7050
    extra_hosts:
    # add extra hosts 
