version: '2'

volumes:
  osinstance1.cerberus.net:
          
networks: 
  cerberusntw:
          
services: 
  osinstance1.cerberus.net:
    extends:
      file: ../base/os-base.yaml
      service: os-base
    container_name: osinstance1.cerberus.net
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
    - ORDERER_HOST=osinstance1.cerberus.net
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../../../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../../../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance1.cerberus.net/msp/:/var/hyperledger/orderer/msp
    - ../../../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance1.cerberus.net/tls/:/var/hyperledger/orderer/tls
    - osinstance1.cerberus.net:/var/hyperledger/production/orderer
    depends_on:
    # add kafka instances
    networks:
    - cerberusntw
    ports:
    - 7150:7050
    extra_hosts:
    # add extra hosts 

