version: "2"
volumes:
  osinstance0.cerberus.net: null
  osinstance1.cerberus.net: null
  osinstance2.cerberus.net: null
  osinstance3.cerberus.net: null
  osinstance4.cerberus.net: null
networks:
  cerberusntw: null
services:
  osinstance0.cerberus.net:
    extends:
      file: ../base/os-base.yaml
      service: os-base
    container_name: osinstance0.cerberus.net
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
    - ORDERER_HOST=osinstance0.cerberus.net
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance0.cerberus.net/msp/:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance0.cerberus.net/tls/:/var/hyperledger/orderer/tls
    - osinstance0.cerberus.net:/var/hyperledger/production/orderer
    depends_on:
    - kafka0.cerberus.net
    - kafka1.cerberus.net
    - kafka2.cerberus.net
    - kafka3.cerberus.net
    - kafka4.cerberus.net
    - kafka5.cerberus.net
    - kafka6.cerberus.net
    networks:
    - cerberusntw
    ports:
    - 7050:7050
    extra_hosts:
    - communicatepr.sipher.cerberus.net:155.138.144.24
    - anchorpr.sipher.cerberus.net:155.138.144.24
    - lead0pr.sipher.cerberus.net:155.138.144.24
    - lead1pr.sipher.cerberus.net:155.138.144.24
  osinstance1.cerberus.net:
    extends:
      file: ../base/os-base.yaml
      service: os-base
    container_name: osinstance1.cerberus.net
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
    - ORDERER_HOST=osinstance1.cerberus.net
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance1.cerberus.net/msp/:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance1.cerberus.net/tls/:/var/hyperledger/orderer/tls
    - osinstance1.cerberus.net:/var/hyperledger/production/orderer
    depends_on:
    - kafka0.cerberus.net
    - kafka1.cerberus.net
    - kafka2.cerberus.net
    - kafka3.cerberus.net
    - kafka4.cerberus.net
    - kafka5.cerberus.net
    - kafka6.cerberus.net
    networks:
    - cerberusntw
    ports:
    - 7150:7050
    extra_hosts:
    - anchorpr.sipher.cerberus.net:155.138.144.24
    - lead0pr.sipher.cerberus.net:155.138.144.24
    - lead1pr.sipher.cerberus.net:155.138.144.24
    - communicatepr.sipher.cerberus.net:155.138.144.24
  osinstance2.cerberus.net:
    extends:
      file: ../base/os-base.yaml
      service: os-base
    container_name: osinstance2.cerberus.net
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
    - ORDERER_HOST=osinstance2.cerberus.net
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance2.cerberus.net/msp/:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance2.cerberus.net/tls/:/var/hyperledger/orderer/tls
    - osinstance2.cerberus.net:/var/hyperledger/production/orderer
    depends_on:
    - kafka0.cerberus.net
    - kafka1.cerberus.net
    - kafka2.cerberus.net
    - kafka3.cerberus.net
    - kafka4.cerberus.net
    - kafka5.cerberus.net
    - kafka6.cerberus.net
    networks:
    - cerberusntw
    ports:
    - 7250:7050
    extra_hosts:
    - anchorpr.sipher.cerberus.net:155.138.144.24
    - lead0pr.sipher.cerberus.net:155.138.144.24
    - lead1pr.sipher.cerberus.net:155.138.144.24
    - communicatepr.sipher.cerberus.net:155.138.144.24
  osinstance3.cerberus.net:
    extends:
      file: ../base/os-base.yaml
      service: os-base
    container_name: osinstance3.cerberus.net
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
    - ORDERER_HOST=osinstance3.cerberus.net
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance3.cerberus.net/msp/:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance3.cerberus.net/tls/:/var/hyperledger/orderer/tls
    - osinstance3.cerberus.net:/var/hyperledger/production/orderer
    depends_on:
    - kafka0.cerberus.net
    - kafka1.cerberus.net
    - kafka2.cerberus.net
    - kafka3.cerberus.net
    - kafka4.cerberus.net
    - kafka5.cerberus.net
    - kafka6.cerberus.net
    networks:
    - cerberusntw
    ports:
    - 7350:7050
    extra_hosts:
    - anchorpr.sipher.cerberus.net:155.138.144.24
    - lead0pr.sipher.cerberus.net:155.138.144.24
    - lead1pr.sipher.cerberus.net:155.138.144.24
    - communicatepr.sipher.cerberus.net:155.138.144.24
  osinstance4.cerberus.net:
    extends:
      file: ../base/os-base.yaml
      service: os-base
    container_name: osinstance4.cerberus.net
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
    - ORDERER_HOST=osinstance4.cerberus.net
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance4.cerberus.net/msp/:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/cerberus.net/orderers/osinstance4.cerberus.net/tls/:/var/hyperledger/orderer/tls
    - osinstance4.cerberus.net:/var/hyperledger/production/orderer
    depends_on:
    - kafka0.cerberus.net
    - kafka1.cerberus.net
    - kafka2.cerberus.net
    - kafka3.cerberus.net
    - kafka4.cerberus.net
    - kafka5.cerberus.net
    - kafka6.cerberus.net
    networks:
    - cerberusntw
    ports:
    - 7450:7050
    extra_hosts:
    - anchorpr.sipher.cerberus.net:155.138.144.24
    - lead0pr.sipher.cerberus.net:155.138.144.24
    - lead1pr.sipher.cerberus.net:155.138.144.24
    - communicatepr.sipher.cerberus.net:155.138.144.24
  zk0:
    extends:
      file: ../base/kafka-base.yaml
      service: zookeeper
    container_name: zk0
    environment:
    - ZOO_MY_ID=1
    - ZOO_SERVERS=server.1=zk0:2888:3888 server.2=zk1:2888:3888 server.3=zk2:2888:3888
      server.4=zk3:2888:3888 server.5=zk4:2888:3888 server.6=zk5:2888:3888 server.7=zk6:2888:3888
    networks:
    - cerberusntw
  zk1:
    extends:
      file: ../base/kafka-base.yaml
      service: zookeeper
    container_name: zk1
    environment:
    - ZOO_MY_ID=2
    - ZOO_SERVERS=server.1=zk0:2888:3888 server.2=zk1:2888:3888 server.3=zk2:2888:3888
      server.4=zk3:2888:3888 server.5=zk4:2888:3888 server.6=zk5:2888:3888 server.7=zk6:2888:3888
    networks:
    - cerberusntw
  zk2:
    extends:
      file: ../base/kafka-base.yaml
      service: zookeeper
    container_name: zk2
    environment:
    - ZOO_MY_ID=3
    - ZOO_SERVERS=server.1=zk0:2888:3888 server.2=zk1:2888:3888 server.3=zk2:2888:3888
      server.4=zk3:2888:3888 server.5=zk4:2888:3888 server.6=zk5:2888:3888 server.7=zk6:2888:3888
    networks:
    - cerberusntw
  zk3:
    extends:
      file: ../base/kafka-base.yaml
      service: zookeeper
    container_name: zk3
    environment:
    - ZOO_MY_ID=4
    - ZOO_SERVERS=server.1=zk0:2888:3888 server.2=zk1:2888:3888 server.3=zk2:2888:3888
      server.4=zk3:2888:3888 server.5=zk4:2888:3888 server.6=zk5:2888:3888 server.7=zk6:2888:3888
    networks:
    - cerberusntw
  zk4:
    extends:
      file: ../base/kafka-base.yaml
      service: zookeeper
    container_name: zk4
    environment:
    - ZOO_MY_ID=5
    - ZOO_SERVERS=server.1=zk0:2888:3888 server.2=zk1:2888:3888 server.3=zk2:2888:3888
      server.4=zk3:2888:3888 server.5=zk4:2888:3888 server.6=zk5:2888:3888 server.7=zk6:2888:3888
    networks:
    - cerberusntw
  zk5:
    extends:
      file: ../base/kafka-base.yaml
      service: zookeeper
    container_name: zk5
    environment:
    - ZOO_MY_ID=6
    - ZOO_SERVERS=server.1=zk0:2888:3888 server.2=zk1:2888:3888 server.3=zk2:2888:3888
      server.4=zk3:2888:3888 server.5=zk4:2888:3888 server.6=zk5:2888:3888 server.7=zk6:2888:3888
    networks:
    - cerberusntw
  zk6:
    extends:
      file: ../base/kafka-base.yaml
      service: zookeeper
    container_name: zk6
    environment:
    - ZOO_MY_ID=7
    - ZOO_SERVERS=server.1=zk0:2888:3888 server.2=zk1:2888:3888 server.3=zk2:2888:3888
      server.4=zk3:2888:3888 server.5=zk4:2888:3888 server.6=zk5:2888:3888 server.7=zk6:2888:3888
    networks:
    - cerberusntw
  kafka0.cerberus.net:
    extends:
      file: ../base/kafka-base.yaml
      service: kafka
    container_name: kafka0.cerberus.net
    environment:
    - KAFKA_BROKER_ID=0
    - KAFKA_ZOOKEEPER_CONNECT=zk0:2181, zk1:2181, zk2:2181, zk3:2181, zk4:2181, zk5:2181,
      zk6:2181
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka0.cerberus.net:9092
    depends_on:
    - zk0
    - zk1
    - zk2
    - zk3
    - zk4
    - zk5
    - zk6
    ports:
    - 9092:9092
    networks:
    - cerberusntw
  kafka1.cerberus.net:
    extends:
      file: ../base/kafka-base.yaml
      service: kafka
    container_name: kafka1.cerberus.net
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=zk0:2181, zk1:2181, zk2:2181, zk3:2181, zk4:2181, zk5:2181,
      zk6:2181
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1.cerberus.net:9092
    depends_on:
    - zk0
    - zk1
    - zk2
    - zk3
    - zk4
    - zk5
    - zk6
    ports:
    - 9093:9092
    networks:
    - cerberusntw
  kafka2.cerberus.net:
    extends:
      file: ../base/kafka-base.yaml
      service: kafka
    container_name: kafka2.cerberus.net
    environment:
    - KAFKA_BROKER_ID=2
    - KAFKA_ZOOKEEPER_CONNECT=zk0:2181, zk1:2181, zk2:2181, zk3:2181, zk4:2181, zk5:2181,
      zk6:2181
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2.cerberus.net:9092
    depends_on:
    - zk0
    - zk1
    - zk2
    - zk3
    - zk4
    - zk5
    - zk6
    ports:
    - 9094:9092
    networks:
    - cerberusntw
  kafka3.cerberus.net:
    extends:
      file: ../base/kafka-base.yaml
      service: kafka
    container_name: kafka3.cerberus.net
    environment:
    - KAFKA_BROKER_ID=3
    - KAFKA_ZOOKEEPER_CONNECT=zk0:2181, zk1:2181, zk2:2181, zk3:2181, zk4:2181, zk5:2181,
      zk6:2181
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3.cerberus.net:9092
    depends_on:
    - zk0
    - zk1
    - zk2
    - zk3
    - zk4
    - zk5
    - zk6
    ports:
    - 9095:9092
    networks:
    - cerberusntw
  kafka4.cerberus.net:
    extends:
      file: ../base/kafka-base.yaml
      service: kafka
    container_name: kafka4.cerberus.net
    environment:
    - KAFKA_BROKER_ID=4
    - KAFKA_ZOOKEEPER_CONNECT=zk0:2181, zk1:2181, zk2:2181, zk3:2181, zk4:2181, zk5:2181,
      zk6:2181
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka4.cerberus.net:9092
    depends_on:
    - zk0
    - zk1
    - zk2
    - zk3
    - zk4
    - zk5
    - zk6
    ports:
    - 9096:9092
    networks:
    - cerberusntw
  kafka5.cerberus.net:
    extends:
      file: ../base/kafka-base.yaml
      service: kafka
    container_name: kafka5.cerberus.net
    environment:
    - KAFKA_BROKER_ID=5
    - KAFKA_ZOOKEEPER_CONNECT=zk0:2181, zk1:2181, zk2:2181, zk3:2181, zk4:2181, zk5:2181,
      zk6:2181
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka5.cerberus.net:9092
    depends_on:
    - zk0
    - zk1
    - zk2
    - zk3
    - zk4
    - zk5
    - zk6
    ports:
    - 9097:9092
    networks:
    - cerberusntw
  kafka6.cerberus.net:
    extends:
      file: ../base/kafka-base.yaml
      service: kafka
    container_name: kafka6.cerberus.net
    environment:
    - KAFKA_BROKER_ID=6
    - KAFKA_ZOOKEEPER_CONNECT=zk0:2181, zk1:2181, zk2:2181, zk3:2181, zk4:2181, zk5:2181,
      zk6:2181
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka6.cerberus.net:9092
    depends_on:
    - zk0
    - zk1
    - zk2
    - zk3
    - zk4
    - zk5
    - zk6
    ports:
    - 9098:9092
    networks:
    - cerberusntw
